version: '3.8'

services:
  jenkins:
    # image: digitech-docker-build.itt.aws.odev.com.au/jenkins:lts
    # image: jenkins/jenkins:latest
    build:
      context: docker
      dockerfile: Dockerfile
    container_name: jenkins
    user: jenkins
    env_file:
      - .env
    environment:
      - AWS_PROFILE=digi-nonprod
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - ./jenkins_data_jobs:/var/jenkins_home/jobs
    restart: unless-stopped
